//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new employee.
        /// </summary>
        public static string addNewEmployee {
            get {
                return ResourceManager.GetString("addNewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add phone number.
        /// </summary>
        public static string addPhoneNumber_Button {
            get {
                return ResourceManager.GetString("addPhoneNumber_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new phone number for employee.
        /// </summary>
        public static string addPhoneNumber_TextBlock {
            get {
                return ResourceManager.GetString("addPhoneNumber_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change employee data.
        /// </summary>
        public static string changeEmployee_Button {
            get {
                return ResourceManager.GetString("changeEmployee_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на x.
        /// </summary>
        public static string closeIcon {
            get {
                return ResourceManager.GetString("closeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete this employee.
        /// </summary>
        public static string deleteEmployee_Button {
            get {
                return ResourceManager.GetString("deleteEmployee_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete phone number.
        /// </summary>
        public static string deletePhoneNumber {
            get {
                return ResourceManager.GetString("deletePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employee phones number list:.
        /// </summary>
        public static string employeePhonesList {
            get {
                return ResourceManager.GetString("employeePhonesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find an employee.
        /// </summary>
        public static string findEmployee {
            get {
                return ResourceManager.GetString("findEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the first name.
        /// </summary>
        public static string hintFirstName {
            get {
                return ResourceManager.GetString("hintFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the first name (optional).
        /// </summary>
        public static string hintFirstNameOptional {
            get {
                return ResourceManager.GetString("hintFirstNameOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the login.
        /// </summary>
        public static string hintLogin {
            get {
                return ResourceManager.GetString("hintLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the middle name (optional).
        /// </summary>
        public static string hintMiddleNameOptional {
            get {
                return ResourceManager.GetString("hintMiddleNameOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the second name (optional).
        /// </summary>
        public static string hintSecondNameOptional {
            get {
                return ResourceManager.GetString("hintSecondNameOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main page.
        /// </summary>
        public static string mainPage {
            get {
                return ResourceManager.GetString("mainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New employee.
        /// </summary>
        public static string newEmployeeTab {
            get {
                return ResourceManager.GetString("newEmployeeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search employee by name.
        /// </summary>
        public static string searchByName {
            get {
                return ResourceManager.GetString("searchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show all employees.
        /// </summary>
        public static string showAllEmployees {
            get {
                return ResourceManager.GetString("showAllEmployees", resourceCulture);
            }
        }
    }
}
